export enum MsgType {
  RETURN = "RETURN",
  CONF = "CONF",
  EXIT = "EXIT",
  RESTART = "RESTART",
  CONNECT = "CONNECT",

  AGENT = "AGENT",
  QRY_CONF = "QRY_CONF",

  MD_SUBS = "MD_SUBS",
  PAUSE_OPEN = "PAUSE_OPEN",
  PAUSE_CLOSE = "PAUSE_CLOSE",
  ACT_ORDER = "ACT_ORDER",
  ACT_CANCEL = "ACT_CANCEL",
  QRY_TRADE = "QRY_TRADE",
  QRY_ORDER = "QRY_ORDER",
  QRY_POSITION = "QRY_POSITION",
  QRY_ACCT = "QRY_ACCT",

  ON_STATUS = "ON_STATUS",
  ON_LOG = "ON_LOG",
  ON_POSITION = "ON_POSITION",
  ON_TRADE = "ON_TRADE",
  ON_ORDER = "ON_ORDER",
  ON_CONTRACT = "ON_CONTRACT",
  ON_BAR = "ON_BAR",
  ON_ACCT = "ON_ACCT",
  ON_AGENT = "ON_AGENT"
}
